# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    assignees:
      - "clouddrove-ci"
    reviewers:
      - "approvers"

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "terraform/_modules/cdn" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "terraform/_modules/certificate" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3
  
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "terraform/_modules/container-registry" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "terraform/_modules/domain" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "terraform/_modules/droplet" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "terraform/_modules/firewall" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "terraform/_modules/kubernetes" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "terraform/_modules/loadbalancer" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "terraform/_modules/monitoring" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "terraform/_modules/spaces" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "terraform/_modules/vpc" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3