name: Gitleaks PR Secret Scan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    uses: clouddrove/github-shared-workflows/.github/workflows/gitleaks-pr-scan.yml@03dcb08c08de8e1798c735f548655e391f924277 # pinned to latest
    secrets: inherit
