name: Module Test Harness

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@3f5f04aeaf2695df870f7e3fff6647ea685b8323
    with:
      provider: digitalocean
      working_directory: ./terraform/sandbox/blr1/
