name: Module Test Harness

on:
  pull_request:

permissions:
  contents: read

jobs:
  complete-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@v2
    with:
      provider: digitalocean
      working_directory: ./terraform/sandbox/blr1/
