name: PR Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr_checks.yml@9db6ce0e27e44d60dfb166a04f7ecddde842ec4f # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'
