name: PR Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-checks.yml@2.1.0
    with:
      types: ${{ inputs.types }}
      requireScope: ${{ inputs.requireScope }}
      subjectPattern: ${{ inputs.subjectPattern }}
      validateSingleCommit: ${{ inputs.validateSingleCommit }}
      checkLabels: ${{ inputs.checkLabels }}
    secrets: inherit
