name: PR Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr_checks.yml@3f5f04aeaf2695df870f7e3fff6647ea685b8323 # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'
