name: terraform workflow
permissions: write-all
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  prod:
    uses: clouddrove/github-shared-workflows/.github/workflows/terraform_workflow.yml@master
    with:
        provider: digitalocean
        working_directory: terraform/sandbox/blr1/ # Specify terraform code directory in repo
        # var_file:           # Name of tfvar file e.g "variable.tfvar"
        approvers: d4kverma # Assignee name for approve apply or destroy step
        terraform_version: 1.5.4 # Specify terraform version e.g 1.3.6
        # destroy:            # If the value is set to true, the workflow proceeds to the destroy step. However, the default value is false
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: "test"     # Digitalocean token
    #   SPACES_ACCESS_KEY_ID:     # Provide spaces access key id if required
    #   SPACES_SECRET_ACCESS_KEY: # Provide spaces secret access key if required