name: tf-checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  blr1-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@v2
    with:
      working_directory: './terraform/sandbox/blr1/'
      provider: none

  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-lint.yml@v2
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
