name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  complete-do-module:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@74df2ef7327ca06f5f7ee4cc7727a6e8b87f0959 # pinned to latest
    with:
      provider: digitalocean
      working_directory: './terraform/sandbox/blr1/'

# Separate job for TFlint workflow call
  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-lint.yml@9db6ce0e27e44d60dfb166a04f7ecddde842ec4f # pinned to latest
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
